# Generated by Django 2.0.7 on 2018-07-17 15:44

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('frame', models.CharField(max_length=20)),
                ('power_train', models.CharField(max_length=20)),
                ('wheels', jsonfield.fields.JSONField(default=[])),
            ],
        ),
    ]
