# Generated by Django 2.0.4 on 2018-07-20 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Report'),
            preserve_default=False,
        ),
    ]
